sudo: required
services:
  - docker

before_install:
  - docker build -t naoufalbelhour/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run naoufalbelhour/react-test npm test -- --coverage

after_success:
  - docker build -t naoufalbelhour/multi-client ./client
  - docker build -t naoufalbelhour/multi-nginx ./nginx
  - docker build -t naoufalbelhour/multi-server ./server
  - docker build -t naoufalbelhour/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push naoufalbelhour/multi-client
  - docker push naoufalbelhour/multi-nginx
  - docker push naoufalbelhour/multi-server
  - docker push naoufalbelhour/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-us-east-2-893816886621
  bucket_path: complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
